Add support to Archiveless collection
openzim/nautilus pull request #63
Opened 2023-07-19 19:17 UTC by FledgeXu

Fix: #60.

2023-07-20 09:24 UTC, rgaudin requested changes
I am surprised to discover that `--archive` was already a non-required argument! 😀

Anyway I think your approach is not right. Most of `check_archiveless_collection` is duplicated code from other parts.

It would be best to adapt or rewrite `test_files` to support both and reduce code duplication.

Also, please add an entry in the CHANGELOG

2023-07-20 09:24 UTC, rgaudin commented on nautiluszim/scraper.py
> +        if self.collection and not self.archive:
At this point `self.collection` always exists (would have failed earlier if not)

2023-07-20 09:24 UTC, rgaudin commented on nautiluszim/scraper.py
> +        with open(self.collection, "r") as fp:
Instead of this we can call `test_collection` beforehand as this is basically a duplicate.
It should probably be renamed. Maybe `load_collection` ?

2023-07-20 09:24 UTC, rgaudin commented
Ah I realize the PR is in Draft ; Sorry 😀

2023-07-20 13:07 UTC, FledgeXu commented
> It would be best to adapt or rewrite test_files to support both and reduce code duplication.

Yeah, that's my plan.


> Ah I realize the PR is in Draft ; Sorry 😀

lol, it's ok.

2023-07-20 20:50 UTC, rgaudin requested changes

2023-07-20 20:50 UTC, rgaudin commented on nautiluszim/scraper.py
> +    def __test_duplicate_file_names(self, files):
```suggestion
    def _ensure_no_duplicate_filenames(self, files):
```

2023-07-20 20:50 UTC, rgaudin commented on nautiluszim/scraper.py
> +        if files:
```py
if not files:
    return
raise XXX
```
Allows getting out of the loop early, reducing stack and indentation

2023-07-20 20:50 UTC, rgaudin commented on nautiluszim/scraper.py
> +        (duplicate_file_names, missing_files, none_url_files, all_file_names)"""
Some names are not understandable and not described either

2023-07-20 20:50 UTC, rgaudin commented on nautiluszim/scraper.py
> +        (duplicate_file_names, missing_files, none_url_files, all_file_names)"""
```py
    def check_collection_filenames(available_filenames: Optional[List[str]] = None) -> tuple()
        """ Check collection filenames for missing URLs or missing member in ZIP file

            all_filenames: list of all target filenames
            missing_filenames: list of entry titles for which a filename is missing
            duplicate_filename: list of target (in ZIM) filenames that are present 2+ times
            local_filenames: list of filenames that are not referencing an URL
```

The list of `non_url_filenames` is used only once so I'd remove it from the function and just loop over `all_filenames` in `test_archiveless_collection` looking for `http`

2023-07-21 09:06 UTC, rgaudin requested changes
One tiny fix remaining

2023-07-21 09:06 UTC, rgaudin commented on nautiluszim/scraper.py
> +    ) -> Tuple[Set[str], List[str], List[str]]:
You should probably cast the set to list when returning to harmonize with the rest

2023-07-21 09:06 UTC, rgaudin commented on nautiluszim/scraper.py
> +            "File(s) referenced in collection but missing:\n - " + "\n - ".join(files)
```suggestion
            "File(s) referenced in collection which are missing:\n - " + "\n - ".join(files)
```

2023-07-21 09:06 UTC, rgaudin commented on nautiluszim/scraper.py
> +            "Files in collection are duplicate:\n - " + "\n - ".join(files)
```suggestion
            "Files in collection which are duplicate:\n - " + "\n - ".join(files)
```

2023-07-21 13:34 UTC, FledgeXu commented on nautiluszim/scraper.py
> +        duplicate_filename = set()
If we don't care about the duplication of the `duplicate_filenames`, we can just use the:
```python
[filename for filename in all_uris if all_uris.count(filename) > 1]
```

2023-07-21 14:15 UTC, rgaudin commented on nautiluszim/scraper.py
> +        duplicate_filename = set()
Exactly. No set is needed and you were not using any of its fearures

2023-07-21 14:15 UTC, rgaudin approved these changes
Thank you!

2023-07-21 14:15 UTC, merged